### ISSUE TITLE
manage.py migrate/check error

### ISSUE THREAD

**Issue by ddrake** [django-cms/djangocms-file#60]
Hi, 
I'm working through the [django-cms tutorial](https://docs.django-cms.org/en/latest/how_to/install.html#miscellaneous-plugins) with Django 4.2.6, django-cms 3.11.4 and django-filer 3.1.0

I ran: pip install djangocms-file, then added 'djangocms_file' to INSTALLED_APPS, but could not migrate because of this error:

> djangocms_file.File.file_src: (fields.E300) Field defines a relation with model 'File', which is either not installed, or is abstract.
> djangocms_file.Folder.folder_src: (fields.E300) Field defines a relation with model 'Folder', which is either not installed, or is abstract.

I got similar errors for djangocms-link, djangocms-picture, djangocms-video and djangocms-googlemap.
I didn't get any errors for djangocms-snippet or djangocms-style.

I'm running Python 3.10.12 on Ubuntu 20.04

Best,
Dow

**Comment by fsbraun** [comment]
@ddrake Is `filer` in installed apps? It defines both the `File` and `Folder` model.

**Comment by ddrake** [comment]
Sorry -- looks like I missed a step or two there!  My bad!  After adding filer to installed apps and migrating, djangocms-file and the other plugins (djangocms-link, djangocms-picture, djangocms-video and djangocms-googlemap) all migrated correctly.  Thanks much for the reply!

**Comment by fsbraun** [comment]
@ddrake Glad to hear it works!
